# Site settings
title: schlichtanders
author: Stephan Sahm
email: Stephan.Sahm@gmx.de
description: "Stephan Sahm's Portfolio. Get to know, what I did and who I was, and be part of what follows."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stephan-sahm-918656b7
  - title: github
    url: http://github.com/schlichtanders
  - title: envelope
    url: mailto:Stephan.Sahm@gmx.de

# Postal address (add as many lines as necessary)
address:
  - line: MÃ¼nchen, Germany
#   - line: Kitchener, ON N2H3V5

# Build settings
markdown: kramdown
permalink: pretty
